import matplotlib.pyplot as plt
from data import data
presupuesto_region = data.groupby("REGIÓN")["PRESUPUESTO CODIFICADO 2024"].sum()
plt.figure(figsize=(10, 6)) 
presupuesto_region.plot(kind="bar", colormap="viridis")
plt.title("Distribución del Presupuesto por Región")
plt.xlabel("Región")
plt.ylabel("Presupuesto")
plt.xticks(rotation=45, ha="right")  
plt.grid(axis="y", linestyle="--", alpha=0.7) 
plt.show()
presupuesto_pais = data.groupby("PAÍS")["PRESUPUESTO CODIFICADO 2024"].sum()
top_10_paises = presupuesto_pais.nlargest(10)
plt.figure(figsize=(12, 8))
top_10_paises.plot(kind="bar", colormap="coolwarm")
plt.title("Top 10 Países con Mayor Presupuesto")
plt.xlabel("País")
plt.ylabel("Presupuesto")
plt.xticks(rotation=90)  
plt.grid(axis="y", linestyle="--", alpha=0.7)
plt.tight_layout()  
plt.show()
presupuesto_gasto = data.groupby("DETALLE DEL GRUPO DE GASTO")["PRESUPUESTO CODIFICADO 2024"].sum()
plt.figure(figsize=(10, 10))
presupuesto_gasto.plot(kind="pie", autopct="%1.1f%%", startangle=90) 
plt.title("Distribución del Presupuesto por Tipo de Gasto")
plt.axis("equal")  
plt.show()
data["EJECUCIÓN %"] = data["PORCENTAJE DE EJECUCIÓN"].astype(float) / 100
ejecucion_promedio = data["EJECUCIÓN %"].mean()
misiones_baja_ejecucion = data[data["EJECUCIÓN %"] < ejecucion_promedio]
ejecucion_region = data.groupby("REGIÓN")["EJECUCIÓN %"].mean()
plt.figure(figsize=(8, 6))
ejecucion_region.plot(kind="bar", colormap="copper")
plt.title("Ejecución Presupuestaria Promedio por Región")
plt.xlabel("Región")
plt.ylabel("Ejecución Promedio (%)")
plt.xticks(rotation=45, ha="right")
plt.grid(axis="y", linestyle="--", alpha=0.7)
plt.show()
ejecucion_pais = data.groupby("PAÍS")["EJECUCIÓN %"].mean()
paises_baja_ejecucion = ejecucion_pais[ejecucion_pais < ejecucion_promedio]

